export default {
    GET_SERVICE_ORDER : "GET_SERVICE_ORDER",
    RECEIVE_SERVICE_ORDER : "RECEIVE_SERVICE_ORDER",

    INSERT_SERVICE_ORDER : "INSERT_SERVICE_ORDER",
    RECEIVE_INSERT_SERVICE_ORDER :  "RECEIVE_INSERT_SERVICE_ORDER",

    CANCEL_SERVICE_ORDER : "CANCEL_SERVICE_ORDER",
    RECEIVE_CANCEL_SERVICE_ORDER : "RECEIVE_CANCEL_SERVICE_ORDER"

}